const mongoose = require("mongoose");
require("dotenv").config();

const Category = require("../models/category");
const Producer = require("../models/producer");
const Size = require("../models/size");
const Gender = require("../models/gender");
const Color = require("../models/color");
const Product = require("../models/product");
const ProductInstance = require("../models/productInstance");

let categories = [{ name: "Shoes" }, { name: "T-shirt" }, { name: "Shorts" }, { name: "Socks" }, { name: "Pants" }];

let producers = [
    { name: "Nike" },
    { name: "Converse" },
    { name: "Jordan" },
    { name: "Jumpman" },
    { name: "WMNS" },
    { name: "Stance" },
];

let sizes = [
    { name: "35" },
    { name: "36" },
    { name: "37" },
    { name: "38" },
    { name: "39" },
    { name: "40" },
    { name: "41" },
    { name: "42" },
    { name: "43" },
    { name: "44" },
    { name: "45" },
    { name: "46" },
    { name: "XXS" },
    { name: "XS" },
    { name: "S" },
    { name: "M" },
    { name: "L" },
    { name: "XL" },
    { name: "XXL" },
];

let genders = [{ name: "Men" }, { name: "Women" }, { name: "Kids" }, { name: "Unisex" }];

let colors = [
    { name: "Green" },
    { name: "Blue" },
    { name: "Red" },
    { name: "Gray" },
    { name: "Black" },
    { name: "White" },
    { name: "Orange" },
];

let products = [
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX PULSE (GS)",
        description: "Description for Product",
        price: 6529,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_1_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX 1 (GS)",
        description: "Description for Product",
        price: 6529,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_2_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX 270 SE (GS)",
        description: "Description for Product",
        price: 6529,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_3_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX PULSE (GS)",
        description: "Description for Product",
        price: 6529,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_4_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX PULSE (GS)",
        description: "Description for Product",
        price: 6529,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_5_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AIR MAX 2013 (GS)",
        description: "Description for Product",
        price: 7549,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_6_MAIN_PHOTO.jpg`,
    },
    {
        producer: 4,
        category: 1,
        name: "Кросівки Jumpman MVP",
        description: "Description for Product",
        price: 4379,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_7_MAIN_PHOTO.jpg`,
    },
    {
        producer: 4,
        category: 1,
        name: "Кросівки Jumpman MVP",
        description: "Description for Product",
        price: 7049,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_8_MAIN_PHOTO.jpg`,
    },
    {
        producer: 4,
        category: 1,
        name: "Кросівки Jumpman MVP",
        description: "Description for Product",
        price: 3279,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_9_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 1,
        name: "Кросівки JORDAN SPIZIKE LOW (GS) Team Red",
        description: "Description for Product",
        price: 6749,
        gender: 3,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_10_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AMBUSH X NIKE AIR MORE UPTEMPO LOW LILAC AND APPLE GREEN",
        description: "Description for Product",
        price: 11399,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_11_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE NOCTA AIR FORCE 1 WHITE",
        description: "Description for Product",
        price: 9499,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_12_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 1,
        name: "Кросівки AIR JORDAN 1 LOW",
        description: "Description for Product",
        price: 7049,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_13_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 1,
        name: "Кросівки Converse AS-1 PRO OX OLIVE GREEN / BLACK",
        description: "Description for Product",
        price: 5199,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_14_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike NIKE AIR MAX 1 PRM DIA DE MUERTOS",
        description: "Description for Product",
        price: 9479,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_15_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike NIKE ZOOM VOMERO 5 PACIFIC MOSS",
        description: "Description for Product",
        price: 9129,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_16_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE SB VERTEBRAE Team Red",
        description: "Description for Product",
        price: 4649,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_17_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike SB Force 58 Premium Light Bone / Sand Drift",
        description: "Description for Product",
        price: 4379,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_18_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike SB Force 58 Team Red / Summit White",
        description: "Description for Product",
        price: 4129,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_19_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike SB Force 58 Vintage Green",
        description: "Description for Product",
        price: 4129,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_20_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE WMNS DUNK LOW PHOTON DUST",
        description: "Description for Product",
        price: 6529,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_21_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE AMBUSH X NIKE AIR MORE UPTEMPO LOW LILAC AND APPLE GREEN",
        description: "Description for Product",
        price: 11399,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_22_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE NOCTA AIR FORCE 1 WHITE",
        description: "Description for Product",
        price: 9499,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_23_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки NIKE WMNS AIR FORCE 1 07",
        description: "Description for Product",
        price: 6529,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_24_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike NIKE AIR MAX 1 PRM DIA DE MUERTOS",
        description: "Description for Product",
        price: 9479,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_25_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 1,
        name: "Кросівки Nike WMNS Zoom Vomero 5 COOL GREY",
        description: "Description for Product",
        price: 8629,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_26_MAIN_PHOTO.jpg`,
    },
    {
        producer: 5,
        category: 1,
        name: "Кросівки WMNS JORDAN STADIUM 90",
        description: "Description for Product",
        price: 7549,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_27_MAIN_PHOTO.jpg`,
    },
    {
        producer: 5,
        category: 1,
        name: "Кросівки WMNS AIR JORDAN 1 MID SE Crinkled Silver Foil",
        description: "Description for Product",
        price: 7349,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_28_MAIN_PHOTO.jpg`,
    },
    {
        producer: 5,
        category: 1,
        name: "Кросівки WMNS Jumpman MVP",
        description: "Description for Product",
        price: 9129,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_29_MAIN_PHOTO.jpg`,
    },
    {
        producer: 5,
        category: 1,
        name: "Кросівки WMNS Jumpman MVP",
        description: "Description for Product",
        price: 9129,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_30_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE M NSW TANK ICON FUTURA",
        description: "Description for Product",
        price: 1379,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_31_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 2,
        name: "Майка JORDAN M Dri-FIT SPRT SLVLS TOP",
        description: "Description for Product",
        price: 1979,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_32_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 2,
        name: "Майка JORDAN M Dri-FIT SPRT SLVLS TOP",
        description: "Description for Product",
        price: 1979,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_33_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE M NSW TREND SLVLS TOP",
        description: "Description for Product",
        price: 2479,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_34_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE M NSW TANK ICON FUTURA",
        description: "Description for Product",
        price: 1379,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_35_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 2,
        name: "Майка JORDAN M ESS STMT ESS TANK",
        description: "Description for Product",
        price: 1999,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_36_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка Nike W NSW ESSNTL RIB CRP TANK",
        description: "Description for Product",
        price: 1979,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_37_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка Nike W NSW ESSNTL RIB CRP TANK",
        description: "Description for Product",
        price: 1979,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_38_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE W NSW WVE DYE JRSY SL TOP A3",
        description: "Description for Product",
        price: 2099,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_39_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE W NSW WVE DYE JRSY SL TOP A3",
        description: "Description for Product",
        price: 2099,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_40_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE W NSW TANK MSCL FUTURA NEW",
        description: "Description for Product",
        price: 1679,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_41_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE W NSW TANK MSCL FUTURA NEW",
        description: "Description for Product",
        price: 1679,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_42_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 2,
        name: "Майка NIKE W NSW TANK MSCL FUTURA NEW",
        description: "Description for Product",
        price: 1679,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_43_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse WORDMARK KNIT SHORT MOSSY SLOTH",
        description: "Description for Product",
        price: 2599,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_44_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE M NSW SW AIR SHORT PK",
        description: "Description for Product",
        price: 3079,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_45_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE M CLUB SHORT WVN",
        description: "Description for Product",
        price: 2549,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_46_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE M CLUB SHORT WVN",
        description: "Description for Product",
        price: 2549,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_47_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE M NSW SW AIR SHORT PK",
        description: "Description for Product",
        price: 3079,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_48_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 3,
        name: "Шорти JORDAN M Dri-FIT SPRT WOVEN SHORT",
        description: "Description for Product",
        price: 2229,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_49_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE M Dri-FIT TOTALITY KNIT 9 IN UL",
        description: "Description for Product",
        price: 1979,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_50_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse CHUCK PATCH SHORT BEACH STONE",
        description: "Description for Product",
        price: 2149,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_51_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse CHUCK PATCH SHORT BEACH STONE",
        description: "Description for Product",
        price: 2149,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_52_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти Nike SB M KEARNY CARGO SHORT AOP",
        description: "Description for Product",
        price: 4329,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_53_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE W NSW WOVEN SHORT GLS",
        description: "Description for Product",
        price: 2729,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_54_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE W NSW ESSNTL MR 5IN WVN SHRT",
        description: "Description for Product",
        price: 2729,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_55_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 3,
        name: "Шорти NIKE W NSW ESSNTL MR 5IN WVN SHRT",
        description: "Description for Product",
        price: 2729,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_56_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse RETRO CHUCK BIKE SHORT BLACK",
        description: "Description for Product",
        price: 1549,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_57_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse CHUCK PATCH SHORT BEACH STONE",
        description: "Description for Product",
        price: 2149,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_58_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 3,
        name: "Шорти Converse CHUCK PATCH SHORT BEACH STONE",
        description: "Description for Product",
        price: 2149,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_59_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 3,
        name: "Шорти JORDAN W WVN SHORT",
        description: "Description for Product",
        price: 3999,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_60_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 3,
        name: "Шорти JORDAN W CHICAGO SHORT",
        description: "Description for Product",
        price: 4649,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_61_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 3,
        name: 'Шорти JORDAN W SPT DMND SHORT 4"',
        description: "Description for Product",
        price: 2729,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_62_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 3,
        name: "Шорти JORDAN W BRKLN FLC SHORT 2",
        description: "Description for Product",
        price: 2729,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_63_MAIN_PHOTO.jpg`,
    },
    {
        producer: 6,
        category: 4,
        name: "Набір шкарпеток Stance BASIC 3 PACK CREW White (3 пари)",
        description: "Description for Product",
        price: 959,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_64_MAIN_PHOTO.jpg`,
    },
    {
        producer: 6,
        category: 4,
        name: "Набір шкарпеток Stance BASIC 3 PACK CREW Multi (3 пари)",
        description: "Description for Product",
        price: 959,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_65_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 4,
        name: "Шкарпетки JORDAN U ED CUSH POLY ANKLE 3PR 144",
        description: "Description for Product",
        price: 1349,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_66_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 4,
        name: "Носки Jordan Everyday Essentials",
        description: "Description for Product",
        price: 1229,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_67_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 4,
        name: "Носки Nike Sportswear Everyday Essential",
        description: "Description for Product",
        price: 1229,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_68_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 4,
        name: "Шкарпетки NIKE U SNKR SOX CREW 3PR 160 NRG AU",
        description: "Description for Product",
        price: 1599,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_69_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 4,
        name: "Шкарпетки JORDAN U EVERYDAY ESSENTIALS CREW 1",
        description: "Description for Product",
        price: 1229,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_70_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 4,
        name: "Шкарпетки JORDAN U EVERYDAY ESSENTIALS CREW 1",
        description: "Description for Product",
        price: 1179,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_71_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 4,
        name: "Шкарпетки NIKE U NSW EVERYDAY ESSENTIAL AN",
        description: "Description for Product",
        price: 729,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_72_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 4,
        name: "Шкарпетки JORDAN U ED CUSH POLY ANKLE 3PR 144",
        description: "Description for Product",
        price: 789,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_73_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 5,
        name: "Штани JORDAN M UNION FLC PANT",
        description: "Description for Product",
        price: 5499,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_74_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse NOVELTY CHUCK PATCH PANT BLACK",
        description: "Description for Product",
        price: 1779,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_75_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE M CLUB KNIT OH PANT",
        description: "Description for Product",
        price: 2729,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_76_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE M CLUB BB CF PANT STACK GX",
        description: "Description for Product",
        price: 3649,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_77_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE M CLUB BB CF PANT STACK GX",
        description: "Description for Product",
        price: 3649,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_78_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE M NK CLUB BB CF PANT ARCH GX",
        description: "Description for Product",
        price: 3649,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_79_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE M NSW CLUB JGGR FT",
        description: "Description for Product",
        price: 2499,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_80_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 5,
        name: "Штани JORDAN M ESS FLC BASELINE PANT",
        description: "Description for Product",
        price: 4149,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_81_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse ELEVATED PANT",
        description: "Description for Product",
        price: 2969,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_82_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 5,
        name: "Штани JORDAN M ESS FLC BASELINE PANT",
        description: "Description for Product",
        price: 4149,
        gender: 1,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_83_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse NOVELTY CHUCK PATCH PANT BLACK",
        description: "Description for Product",
        price: 1779,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_84_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE W NSW PHNX FLC OS AOP SWTPNT",
        description: "Description for Product",
        price: 4149,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_85_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE W NSW PHNX FLC HR OS PANT",
        description: "Description for Product",
        price: 3429,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_86_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE W NSW PHNX FLC HR OS PANT",
        description: "Description for Product",
        price: 3429,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_87_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse RELAXED WIDE LEG",
        description: "Description for Product",
        price: 2549,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_88_MAIN_PHOTO.jpg`,
    },
    {
        producer: 1,
        category: 5,
        name: "Штани NIKE W NSW TCH FLC MR JGGR",
        description: "Description for Product",
        price: 4009,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_89_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse STAR CHEV FLEECE PANT FT CLOUDY DAZE",
        description: "Description for Product",
        price: 1779,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_90_MAIN_PHOTO.jpg`,
    },
    {
        producer: 2,
        category: 5,
        name: "Штани Converse STAR CHEV FLEECE PANT FT CLOUDY DAZE",
        description: "Description for Product",
        price: 1269,
        gender: 4,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_91_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 5,
        name: "Брюки Jordan W FLT FLC PANT SSNL",
        description: "Description for Product",
        price: 3359,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_92_MAIN_PHOTO.jpg`,
    },
    {
        producer: 3,
        category: 5,
        name: "Брюки Jordan W WVN PANT",
        description: "Description for Product",
        price: 3869,
        gender: 2,
        photo: `${process.env.STATIC_URL}/images/MAIN_PHOTOS/PRODUCT_93_MAIN_PHOTO.jpg`,
    },
];

let productInstances = [
    { product: 1, color: 1, size: 1 },
    { product: 1, color: 2, size: 2 },
    { product: 1, color: 3, size: 3 },
    { product: 2, color: 4, size: 1 },
    { product: 2, color: 1, size: 2 },
    { product: 2, color: 2, size: 3 },
    { product: 3, color: 3, size: 1 },
    { product: 3, color: 4, size: 2 },
    { product: 3, color: 1, size: 3 },
    { product: 4, color: 2, size: 1 },
    { product: 4, color: 4, size: 2 },
    { product: 4, color: 3, size: 3 },
    { product: 5, color: 1, size: 1 },
    { product: 5, color: 2, size: 2 },
    { product: 5, color: 3, size: 3 },
    { product: 6, color: 4, size: 1 },
    { product: 6, color: 2, size: 2 },
    { product: 6, color: 3, size: 3 },
    { product: 7, color: 1, size: 1 },
    { product: 7, color: 4, size: 2 },
    { product: 7, color: 3, size: 3 },
    { product: 8, color: 1, size: 1 },
    { product: 8, color: 2, size: 2 },
    { product: 8, color: 3, size: 5 },
    { product: 9, color: 1, size: 4 },
    { product: 9, color: 2, size: 3 },
    { product: 9, color: 3, size: 2 },
    { product: 10, color: 1, size: 1 },
    { product: 10, color: 2, size: 2 },
    { product: 10, color: 3, size: 3 },
    { product: 11, color: 1, size: 6 },
    { product: 11, color: 2, size: 7 },
    { product: 11, color: 3, size: 8 },
    { product: 12, color: 1, size: 9 },
    { product: 12, color: 2, size: 10 },
    { product: 12, color: 3, size: 11 },
    { product: 13, color: 1, size: 11 },
    { product: 13, color: 2, size: 12 },
    { product: 13, color: 3, size: 11 },
    { product: 14, color: 1, size: 10 },
    { product: 14, color: 2, size: 9 },
    { product: 14, color: 3, size: 8 },
    { product: 15, color: 1, size: 10 },
    { product: 15, color: 2, size: 11 },
    { product: 15, color: 3, size: 12 },
    { product: 16, color: 1, size: 10 },
    { product: 16, color: 2, size: 9 },
    { product: 16, color: 3, size: 8 },
    { product: 17, color: 1, size: 7 },
    { product: 17, color: 2, size: 9 },
    { product: 17, color: 3, size: 11 },
    { product: 18, color: 1, size: 8 },
    { product: 18, color: 2, size: 10 },
    { product: 18, color: 3, size: 7 },
    { product: 19, color: 1, size: 11 },
    { product: 19, color: 2, size: 8 },
    { product: 19, color: 3, size: 12 },
    { product: 20, color: 1, size: 12 },
    { product: 20, color: 2, size: 7 },
    { product: 20, color: 3, size: 9 },
    { product: 21, color: 1, size: 11 },
    { product: 21, color: 2, size: 6 },
    { product: 21, color: 3, size: 8 },
    { product: 22, color: 1, size: 9 },
    { product: 22, color: 2, size: 12 },
    { product: 22, color: 3, size: 6 },
    { product: 23, color: 1, size: 7 },
    { product: 23, color: 2, size: 11 },
    { product: 23, color: 3, size: 9 },
    { product: 24, color: 1, size: 6 },
    { product: 24, color: 2, size: 8 },
    { product: 24, color: 3, size: 10 },
    { product: 25, color: 1, size: 10 },
    { product: 25, color: 2, size: 9 },
    { product: 25, color: 3, size: 11 },
    { product: 26, color: 1, size: 6 },
    { product: 26, color: 2, size: 12 },
    { product: 26, color: 3, size: 10 },
    { product: 27, color: 1, size: 9 },
    { product: 27, color: 2, size: 11 },
    { product: 27, color: 3, size: 7 },
    { product: 28, color: 1, size: 7 },
    { product: 28, color: 2, size: 8 },
    { product: 28, color: 3, size: 12 },
    { product: 29, color: 1, size: 10 },
    { product: 29, color: 2, size: 11 },
    { product: 29, color: 3, size: 7 },
    { product: 30, color: 1, size: 8 },
    { product: 30, color: 2, size: 9 },
    { product: 30, color: 3, size: 6 },
    { product: 31, color: 1, size: 17 },
    { product: 31, color: 2, size: 15 },
    { product: 31, color: 3, size: 14 },
    { product: 32, color: 1, size: 13 },
    { product: 32, color: 2, size: 19 },
    { product: 32, color: 3, size: 14 },
    { product: 33, color: 1, size: 18 },
    { product: 33, color: 2, size: 16 },
    { product: 33, color: 3, size: 18 },
    { product: 34, color: 1, size: 19 },
    { product: 34, color: 2, size: 17 },
    { product: 34, color: 3, size: 15 },
    { product: 35, color: 1, size: 15 },
    { product: 35, color: 2, size: 14 },
    { product: 35, color: 3, size: 17 },
    { product: 36, color: 1, size: 14 },
    { product: 36, color: 2, size: 16 },
    { product: 36, color: 3, size: 16 },
    { product: 37, color: 1, size: 18 },
    { product: 37, color: 2, size: 15 },
    { product: 37, color: 3, size: 16 },
    { product: 38, color: 1, size: 16 },
    { product: 38, color: 2, size: 19 },
    { product: 38, color: 3, size: 17 },
    { product: 39, color: 1, size: 15 },
    { product: 39, color: 2, size: 17 },
    { product: 39, color: 3, size: 14 },
    { product: 40, color: 1, size: 13 },
    { product: 40, color: 2, size: 15 },
    { product: 40, color: 3, size: 18 },
    { product: 41, color: 1, size: 18 },
    { product: 41, color: 2, size: 17 },
    { product: 41, color: 3, size: 14 },
    { product: 42, color: 1, size: 19 },
    { product: 42, color: 2, size: 18 },
    { product: 42, color: 3, size: 17 },
    { product: 43, color: 1, size: 15 },
    { product: 43, color: 2, size: 14 },
    { product: 43, color: 3, size: 15 },
    { product: 44, color: 1, size: 16 },
    { product: 44, color: 2, size: 19 },
    { product: 44, color: 3, size: 14 },
    { product: 45, color: 1, size: 17 },
    { product: 45, color: 2, size: 13 },
    { product: 45, color: 3, size: 15 },
    { product: 46, color: 1, size: 18 },
    { product: 46, color: 2, size: 19 },
    { product: 46, color: 3, size: 14 },
    { product: 47, color: 1, size: 14 },
    { product: 47, color: 2, size: 16 },
    { product: 47, color: 3, size: 19 },
    { product: 48, color: 1, size: 13 },
    { product: 48, color: 2, size: 17 },
    { product: 48, color: 3, size: 16 },
    { product: 49, color: 1, size: 15 },
    { product: 49, color: 2, size: 19 },
    { product: 49, color: 3, size: 16 },
    { product: 50, color: 1, size: 14 },
    { product: 50, color: 2, size: 13 },
    { product: 50, color: 3, size: 16 },
    { product: 51, color: 3, size: 15 },
    { product: 52, color: 1, size: 15 },
    { product: 52, color: 2, size: 19 },
    { product: 52, color: 3, size: 17 },
    { product: 53, color: 1, size: 17 },
    { product: 53, color: 2, size: 14 },
    { product: 53, color: 3, size: 16 },
    { product: 54, color: 1, size: 19 },
    { product: 54, color: 2, size: 17 },
    { product: 54, color: 3, size: 13 },
    { product: 55, color: 1, size: 15 },
    { product: 55, color: 2, size: 16 },
    { product: 55, color: 3, size: 19 },
    { product: 56, color: 1, size: 13 },
    { product: 56, color: 2, size: 18 },
    { product: 56, color: 3, size: 17 },
    { product: 57, color: 1, size: 16 },
    { product: 57, color: 2, size: 17 },
    { product: 57, color: 3, size: 18 },
    { product: 58, color: 1, size: 18 },
    { product: 58, color: 2, size: 13 },
    { product: 58, color: 3, size: 19 },
    { product: 59, color: 1, size: 15 },
    { product: 59, color: 2, size: 16 },
    { product: 59, color: 3, size: 14 },
    { product: 60, color: 1, size: 17 },
    { product: 60, color: 2, size: 18 },
    { product: 60, color: 3, size: 15 },
    { product: 61, color: 1, size: 16 },
    { product: 61, color: 2, size: 14 },
    { product: 61, color: 3, size: 18 },
    { product: 62, color: 1, size: 17 },
    { product: 62, color: 2, size: 19 },
    { product: 62, color: 3, size: 15 },
    { product: 63, color: 1, size: 18 },
    { product: 63, color: 2, size: 16 },
    { product: 63, color: 3, size: 13 },
    { product: 64, color: 1, size: 15 },
    { product: 64, color: 2, size: 14 },
    { product: 64, color: 3, size: 19 },
    { product: 65, color: 1, size: 18 },
    { product: 65, color: 2, size: 17 },
    { product: 65, color: 3, size: 13 },
    { product: 66, color: 1, size: 16 },
    { product: 66, color: 2, size: 15 },
    { product: 66, color: 3, size: 18 },
    { product: 67, color: 1, size: 19 },
    { product: 67, color: 2, size: 14 },
    { product: 67, color: 3, size: 17 },
    { product: 68, color: 1, size: 15 },
    { product: 68, color: 2, size: 16 },
    { product: 68, color: 3, size: 13 },
    { product: 69, color: 1, size: 17 },
    { product: 69, color: 2, size: 18 },
    { product: 69, color: 3, size: 19 },
    { product: 70, color: 1, size: 14 },
    { product: 70, color: 2, size: 15 },
    { product: 70, color: 3, size: 16 },
    { product: 71, color: 1, size: 17 },
    { product: 71, color: 2, size: 18 },
    { product: 71, color: 3, size: 19 },
    { product: 72, color: 1, size: 13 },
    { product: 72, color: 2, size: 14 },
    { product: 72, color: 3, size: 15 },
    { product: 73, color: 1, size: 16 },
    { product: 73, color: 2, size: 17 },
    { product: 73, color: 3, size: 18 },
    { product: 74, color: 1, size: 19 },
    { product: 74, color: 2, size: 13 },
    { product: 74, color: 3, size: 14 },
    { product: 75, color: 1, size: 15 },
    { product: 75, color: 2, size: 16 },
    { product: 75, color: 3, size: 17 },
    { product: 76, color: 1, size: 18 },
    { product: 76, color: 2, size: 19 },
    { product: 76, color: 3, size: 13 },
    { product: 77, color: 1, size: 14 },
    { product: 77, color: 2, size: 15 },
    { product: 77, color: 3, size: 16 },
    { product: 78, color: 1, size: 17 },
    { product: 78, color: 2, size: 18 },
    { product: 78, color: 3, size: 19 },
    { product: 79, color: 1, size: 13 },
    { product: 79, color: 2, size: 14 },
    { product: 79, color: 3, size: 15 },
    { product: 80, color: 1, size: 16 },
    { product: 80, color: 2, size: 17 },
    { product: 80, color: 3, size: 18 },
    { product: 81, color: 1, size: 19 },
    { product: 81, color: 2, size: 13 },
    { product: 81, color: 3, size: 14 },
    { product: 82, color: 2, size: 16 },
    { product: 82, color: 3, size: 17 },
    { product: 83, color: 1, size: 18 },
    { product: 83, color: 2, size: 19 },
    { product: 83, color: 3, size: 13 },
    { product: 84, color: 1, size: 14 },
    { product: 84, color: 2, size: 15 },
    { product: 84, color: 3, size: 16 },
    { product: 85, color: 1, size: 17 },
    { product: 85, color: 2, size: 18 },
    { product: 85, color: 3, size: 19 },
    { product: 86, color: 1, size: 13 },
    { product: 86, color: 2, size: 14 },
    { product: 86, color: 3, size: 15 },
    { product: 87, color: 1, size: 16 },
    { product: 87, color: 2, size: 17 },
    { product: 87, color: 3, size: 18 },
    { product: 88, color: 1, size: 19 },
    { product: 88, color: 2, size: 13 },
    { product: 88, color: 3, size: 14 },
    { product: 89, color: 1, size: 15 },
    { product: 89, color: 2, size: 16 },
    { product: 89, color: 3, size: 17 },
    { product: 90, color: 1, size: 18 },
    { product: 90, color: 2, size: 19 },
    { product: 90, color: 3, size: 13 },
    { product: 91, color: 1, size: 14 },
    { product: 91, color: 2, size: 15 },
    { product: 91, color: 3, size: 16 },
    { product: 92, color: 1, size: 17 },
    { product: 92, color: 2, size: 18 },
    { product: 92, color: 3, size: 19 },
    { product: 93, color: 1, size: 13 },
    { product: 93, color: 2, size: 14 },
    { product: 93, color: 3, size: 15 },
];

const seedData = async () => {
    try {
        await mongoose.connect(process.env.DB_URL);
        await mongoose.connection.dropDatabase();
        await mongoose.connection.close();

        await mongoose.connect(process.env.DB_URL);

        categories = await Category.insertMany(categories);
        producers = await Producer.insertMany(producers);
        sizes = await Size.insertMany(sizes);
        genders = await Gender.insertMany(genders);
        colors = await Color.insertMany(colors);

        products = products.map((item) => ({
            ...item,
            producer: producers[item.producer - 1]._id,
            gender: genders[item.gender - 1]._id,
            category: categories[item.category - 1]._id,
        }));

        products = await Product.insertMany(products);

        productInstances = productInstances.map((item) => ({
            size: sizes[item.size - 1]._id,
            color: colors[item.color - 1]._id,
            product: products[item.product - 1]._id,
        }));

        await ProductInstance.insertMany(productInstances);

        console.log("Seed data inserted successfully");
    } catch (error) {
        console.error("Error seeding data:", error);
    } finally {
        mongoose.connection.close();
    }
};

seedData();
